baseURL = 'https://example.org/'
title = 'My New Hugo Site'
baseurl = "/"
languageCode = "en-us"
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
theme = "PaperMod"
paginate = 5
